### ISSUE TITLE
Error when creating nlp from cfg

### ISSUE THREAD

**Issue by cielonet** [br0kej/FASER#1]
Was getting some errors when generating esil and disasm from cfg. 
```Error creating file "test_file_cfg"-dis-singles.txt: No such file or directory (os error 2)```

I looks like it was adding a ```"``` to the text file.

I modified the code and it works now. I will continue to look at other features to make sure no other bugs are found.
```
    /// Generates a file containing every instruction within each of the functions
    /// within the AGFJFile.
    ///
    /// This ignores control flow and simple iterates the JSON objects from the top to
    /// the bottom.
    pub fn generate_linear_bb_walk(mut self, esil: bool) {
        //let fname_string: PathBuf = get_save_file_path(&self.filename, &self.output_path, None, None);
        //let fname_string = if esil {format!("{:?}-esil-singles.txt", fname_string)} else {format!("{:?}-dis-singles.txt", fname_string)};

        let fname_string: PathBuf = get_save_file_path(&self.filename, &self.output_path, None, None);
        let fname_string = if esil {format!("{}-esil-singles.txt", fname_string.display())} else {format!("{}-dis-singles.txt", fname_string.display())};

        if !Path::new(&fname_string).exists() {
            self.load_and_deserialize()
                .expect("Unable to load and desearlize JSON");

            let (sender, receiver) = channel();

            self.functions.unwrap().par_iter_mut().for_each_with(
                sender,
                |s, func: &mut Vec<AGFJFunc>| {
                    s.send(func[0].get_function_instructions(esil, &self.min_blocks, self.reg_norm))
                        .unwrap()
                },
            );

            let res: Vec<Vec<String>> = receiver.iter().filter(|x| x.is_some()).flatten().collect();

            //let write_file = File::create(fname_string).unwrap();
            let write_file = match File::create(&fname_string) {
                Ok(file) => file,
                Err(e) => {
                    //eprintln!("Error creating file: {}", e);
                    eprintln!("Error creating file {}: {}", fname_string, e);
                    return;
                }
            };

            let mut writer = BufWriter::new(&write_file);

            for func in res {
                for bb in func {
                    writer
                        .write_all(bb.as_bytes())
                        .expect("Unable to write bytes.");
                    writer.write_all(b"\n").expect("Unable to write bytes.");
                }
            }
        }
    }
```

**Comment by cielonet** [comment]
I can tell you right now funcstring is crashing as well. Going to work on this will update changes.
```
thread 'main' panicked at src/files.rs:230:53:
Failed to create writer: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x559fd5497c26 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93```

**Comment by cielonet** [comment]
So it looks like I've had to modify various parts of the code so that the``` fname_string ```is used with ```.display()``` while also removing the :?
```
# let fname_string = format!("{}-efs.json", fname_string.display());
let fname_string = format!("{:?}-dfs.json", fname_string); -> let fname_string = format!("{}-dfs.json", fname_string.display());```
making these changes avoids file not found error and directories being created with double quotes

**Comment by cielonet** [comment]
When generating graphs from cfg's
```thread '<unnamed>' panicked at src/agfj.rs:381:57:```
Is fixed with the following code.
```  
 pub fn generate_attributed_cfg(
        &self,
        path: &PathBuf,
        min_blocks: &u16,
        output_path: &PathBuf,
        feature_type: FeatureType,
        architecture: &String,
    ) {
        let full_output_path = get_save_file_path(path, output_path, None, None);
        check_or_create_dir(&full_output_path);
        let file_name = path.file_name().unwrap();
        let binding = file_name.to_string_lossy().to_string();

        let binary_name: Vec<_> = binding.split(".j").collect();

        let function_name = if self.name.chars().count() > 100 {
            &self.name[..75]
        } else {
            &self.name
        };

        let fname_string = format!(
            "{}/{:?}-{}.json",
            &full_output_path.display(), binary_name[0], function_name # Here as well!!!
        );```

**Comment by br0kej** [comment]
Hey @cielonet! Thank you for reporting this and doing a grand job in finding the root causes! I missed the notification but will investigate and push the relevant fixes this week. It looks like my project wide `PathBuf` refactor has messed up the NLP related stuff!

**Comment by br0kej** [comment]
Hey @cielonet  - I have pushed the relevant fixes to https://github.com/br0kej/bin2ml on `main`. Could you pull the most recent source from that repo, build it and then report back to see if its working for you?

**Comment by cielonet** [comment]
doesn't look like it was fixed because the generated files now have quotes in the start of the filename.
```
bin2ml generate graphs --data-type cfg --path file_cfg.json --output-path . --num-threads 8 -f gemini
'"file_cfg"-fcn.0000525c.json'
'"file_cfg"-fcn.000052f0.json'
'"file_cfg"-fcn.00005412.json'
```

**Comment by cielonet** [comment]
removing an extra `:?` fixes this issue in `agfj.rs`

```
        let fname_string = format!(
            "{}/{}-{}.json",
            &full_output_path.to_string_lossy(), binary_name[0], function_name
```

**Comment by br0kej** [comment]
Doh! Thank you again @cielonet! Fix just pushed 👍🏼 Going to close now.
